name: 'dbdemos_dbt_c360'

config-version: 2
version: '0.1'

profile: 'dbdemos_dbt_c360'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbdemos_dbt_c360:
      materialized: table
      staging:
        materialized: view
        
  dbt_artifacts:
    +database: mchan_dbt_monitoring_db
    +schema: mchan_dbt_monitoring_db
    staging:
     +database: mchan_dbt_monitoring_db














