dbdemos_dbt_c360:
  target: local
  outputs:
    #run DBT locally from your IDEA and execute on a SQL warehouse (https://docs.getdbt.com/reference/warehouse-setups/databricks-setup)
    #Make sure you have pip install dbt-databricks in your local env
    #Run the project locally with:
    #DBT_DATABRICKS_HOST=xxx.cloud.databricks.com  DBT_DATABRICKS_HTTP_PATH=/sql/1.0/warehouses/xxxx DBT_DATABRICKS_TOKEN=dapixxxx dbt run
    local:
      type: databricks
      catalog: hive_metastore
      schema: mchan_dbt_demo
      host: e2-demo-field-eng.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ead10bf07050390f
      token: dapif217f11245fc11071d024ae561ea7e29


