version: 2

models:
  - name: t2_silver_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: churn
        tests:
          - accepted_values:
              values: [1, 0]
  - name: t2_silver_orders
    columns:
      - name: order_id
        tests:
          - unique
      - name: user_id
        tests:
          - relationships:
              to: ref('t2_silver_users')
              field: user_id
              
              
              
              
              
              
              
              